### ISSUE TITLE
is this repo still alive?

### ISSUE THREAD

**Issue by lyonsdpy** [Juniper/go-netconf#112]

**Comment by nemith** [comment]
This was my first Project in Go back when i worked at Juniper.  I have moved onto many different companies since then and have a need for go-netconf again.  I think this project is need of a v2 rewrite and I have started that however it may take some time for the API and the features to stabilize.

I will be working on it mostly here: https://github.com/nemith/go-netconf/tree/v2 and tracking it this in #24 

Is there anything in particular you are looking for?

**Comment by hellt** [comment]
I know this may sound like unsolicited advice, but why don't we, as a community, try to make a single package strong enough?
There is already a solid foundation made by @carlmontanari in https://github.com/scrapli/scrapligo with netconf support lacking just some RPCs.

**Comment by nemith** [comment]
Scrapligo seems like it is trying to be more than just a netconf library.  This is trying to be low-level as possible and stick to the RFCs and then be able to be extended by other libraries to add additional functionality.  Scrapligo could use the rewrite if they wanted but seems like it's goals are a bit different.

**Comment by nemith** [comment]
So i am going to answer "Yes".  I am trying to revive some some life into this library which has been stale for too long.  And I am going to close this issue for now.
